
task :test_assertion_ripper do
  sh 'ruby1.9.0 test/assertion_ripper_suite.rb'
  sh 'ruby1.9.1 test/assertion_ripper_suite.rb'
end

task :test_assert2 => :test_assertion_ripper do
  sh 'ruby1.9.0 test/assert2_suite.rb'
  sh 'ruby1.9.0 test/assert2_utilities_suite.rb'
  # TODO sh 'ruby1.9.1 test/assert2_suite.rb'
end

task :test_ripdoc => :test_assert2 do
  sh 'ruby1.9.0 test/ripdoc_suite.rb'
  # sh 'ruby1.9.1 test/ripdoc_suite.rb'
end

task :test_assert_xhtml => :test_ripdoc do
  sh 'ruby1.9.0 test/assert_xhtml_suite.rb'
  # sh 'ruby1.9.1 test/assert_xhtml_suite.rb'
end

task :test => :test_assert_xhtml

task :default => :test

task :int => :default do
  sh 'svn commit --message development'
  sh 'svn commit --message development lib/assert2/common'
  sh 'svn update ..'
end

task :zip => :default do
  system 'zip -f assert21.zip '
end

task :todo do
  sh 'find .. -name \*rb | xargs grep TODO'
end

task :fixme do
  sh 'find .. -name \*rb | xargs grep FIXME'
end
