
task :test_assert2 do
  sh 'ruby1.9 test/assert2_test.rb'
end

task :test_ripdoc => :test_assert2 do
  sh 'ruby1.9 test/ripdoc_test.rb'
end

task :test_assert_xhtml => :test_ripdoc do
  sh 'ruby1.9 test/assert_xhtml_test.rb'
end

task :default => :test_assert_xhtml

task :zip => :default do
  system 'zip -f assert21.zip '
end
