
task :test_assert2 do
  sh 'ruby1.9 test/assert2_test.rb'
end

task :test_ripdoc => :test_assert2 do
  sh 'ruby1.9 test/ripdoc_test.rb'
end

task :test_assert_xhtml => :test_ripdoc do
  sh 'ruby1.9 test/assert_xhtml_test.rb'
end

task :test => :test_assert_xhtml

task :default => :test

task :int => :default do
  sh 'svn commit --message development'
  sh 'svn commit --message development lib/common'
  sh 'svn update ..'
end

task :zip => :default do
  system 'zip -f assert21.zip '
end
