
task :default do
  sh 'ruby1.8.6 test/ruby_reflector_suite.rb'
  sh 'ruby1.8.6 test/assert2_suite.rb'
  sh 'ruby1.8.6 test/assert2_xpath_suite.rb'
  sh 'ruby1.8.6 test/assert2_utilities_suite.rb'
  #sh 'ruby1.8.6 test/assert2_shoulda_suite.rb'
end

task :int => :default do
  sh 'svn commit --message development'
  sh 'svn update ..'
end